src/Entity/Page.php
<?php


namespace App\Entity;


class Page
{
    public $isFolder = false;
    public $hasReadme = false;
    public $mime = "";
    public $name;
    public $path;
    public $subLinks = [];
    public $content;

    public function getType(): string
    {
        return explode("/", $this->mime)[0];
    }
}

src/Controller/EmbeddedController.php
<?php


namespace App\Controller;


use App\Annotations\RouteExposed;
use App\Services\TreeLoader\TreeLoader;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class EmbeddedController
 * @package App\Controller
 */
class EmbeddedController extends AbstractController
{
    /**
     * @Route("/_/left", name="articles_tree")
     * @RouteExposed()
     */
    public function leftDefaultMenu(TreeLoader $treeLoader, RequestStack $requestStack)
    {
        $webpath = $requestStack->getMasterRequest()->attributes->get("webpath", "/");
        $articlesTree = $treeLoader->listAllFiles();
        $indexedArticles = $treeLoader->indexedFiles;
        return $this->json(["path" => $webpath, "nav" => $articlesTree, "indexedArticles" => $indexedArticles]);
    }
}

src/Controller/System/EmbeddedController.php
<?php


namespace App\Controller\System;


use App\Entity\Page;
use App\Security\RegistrationEnabledChecker;
use App\Security\SecurityDisabledChecker;
use App\Services\StorageManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class EmbeddedController extends AbstractController
{
    public function leftMenu($path = "", StorageManager $manager)
    {
        $homePage       = new Page();
        $manager->listAllFiles("", $homePage);
        $homePage->name = "Home";
        $homePage->path = "readme";

        return $this->render("embedded/left.html.twig", ["nav" => $homePage, "path" => $path]);
    }

    public function navbar(SecurityDisabledChecker $securityDisabledChecker, RegistrationEnabledChecker $registrationEnabledChecker)
    {
        return $this->render("embedded/top.html.twig", [
            "security_enabled"     => !$securityDisabledChecker->check(),
            "registration_enabled" => $registrationEnabledChecker->check(),
        ]);
    }

}

templates/embedded/left.html.twig
{% macro menuItem(nav,par,dept,path) %}
    {% import _self as macros %}

    <a id="file-{{ nav.path }}" {% if nav.path==path %}class="is-active"{% endif %}

            {% if nav.isFolder and nav.path~"/" ==path %}class="is-active"{% endif %}
            {% if nav.hasReadme and nav.path~"/readme.md" ==path %}class="is-active"{% endif %}

       href="{{ path("knowledge_read",{"path":nav.path}) }}{% if nav.isFolder %}/{% endif %}#file-{{ nav.path }}">
        {% if nav.hasReadme %}
            <span class="icon  has-text-link">
            <i class="fas fa-folder"></i>
</span>
        {% elseif nav.isFolder %}
            <span class="icon has-text-primary">
            <i class="fad fa-folder"></i>
                </span>
        {% else %}
            <span class="icon has-text-info">

                {% if nav.type=="image" %}
                    <i class="fas fa-image"></i>
                {% elseif nav.type=="video" %}
                    <i class="fas fa-video"></i>
                {% else %}
                    <i class="fas fa-file"></i>

                {% endif %}
            </span>
        {% endif %}

        {{ nav.name|titling }}
    </a>
    {% if nav.isFolder %}
        <ul>
            {% for sublink in nav.subLinks %}
                {% set at=par ~ loop.index0 %}
                <li>
                    {{ macros.menuItem(sublink,at,dept+1,path) }}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endmacro %}
{% import _self as macros %}

<form class="top-left" action="{{ path("search_action") }}">
    <input type="text" placeholder="search" name="q"/>
    <button><i class="fad fa-search"></i></button>
    <a href="#" onclick="hideLeft()" class="pull-right"><i class="fad fa-angle-double-left"></i></a>

</form>
<aside class="left-menu">

    <ul class="menu-list">
        <li>
            <a {% if path =="readme" %} class="is-active"{% endif %}
                    href="{{ path('knowledge_read_home') }}">
                <i class="fad fa-home"></i> Home
            </a>
        </li>
        {% for item in nav.subLinks %}
            {% set dept=0 %}
            {% set at=loop.index0 %}
            <li>
                {{ macros.menuItem(item,at,dept,path) }}
            </li>
        {% endfor %}
    </ul>
</aside>
{% if not is_granted("ROLE_USER") %}
    <a class="login-button" href="{{ path('user_login') }}"> <i class="fad fa-user"></i> Login</a><br/>
{% else %}
    <a class="login-button" href="{{ path('user_logout') }}"> <i class="fad fa-power-off"></i> Logout</a><br/>
{% endif %}